### ISSUE TITLE
F claim

### ISSUE THREAD

**Issue by ghost** [BlockHorizons/FactionsPE#53]
F claim is buggy.

You can claim any territory , power doesn't matter.

Try add and f bank, f top money, f top time online

**Comment by Kris-Driv** [comment]
Yes. This is known issue and well known, but there is problem that claim mechanics are implemented directly as it is from MassiveCraft's plugin and is identical. Can you please explain what are the expected behavior?

Top command already exists, but is ordered by power as of now. Thanks for suggestion I'll definitely add this.

**Comment by ghost** [comment]
Actually with /f claim you can claim without faction power to be highest them factions territory who you want to claim

**Comment by Kris-Driv** [comment]
I added your suggestion about ``/f top online`` currently can't test. I don't have any factions created on test server. Commit: https://github.com/BlockHorizons/FactionsPE/commit/361889d041280138ac4bcef7b4d3fe7fdac0d017

**Comment by ghost** [comment]
And fix issue with "created XXX years ago"

**Comment by Kris-Driv** [comment]
Alright.

**Comment by Kris-Driv** [comment]
Fixed!
